SELECT
  o.ID,
  o.NUM_VENDA_FK,
  o.PROTOCOLO,
  o.NOME_USUARIO_FK,
  o.DESCRICAO,
  o.STATUS_OCORRENCIA,
  o.DT_OCORRENCIA,
  o.HORA_OCORRENCIA
FROM dbo.OCORRENCIAS o
LEFT JOIN dw.fat_analise_inadimplencia_v4 v4 ON v4.NUM_VENDA = o.NUM_VENDA_FK
WHERE v4.NUM_VENDA IS NULL
ORDER BY o.NUM_VENDA_FK DESC, o.DT_OCORRENCIA DESC, o.HORA_OCORRENCIA DESC;

SELECT
  o.NUM_VENDA_FK,
  COUNT(*) AS TOTAL_OCORRENCIAS,
  MIN(o.DT_OCORRENCIA) AS PRIMEIRA_OCORRENCIA,
  MAX(o.DT_OCORRENCIA) AS ULTIMA_OCORRENCIA
FROM dbo.OCORRENCIAS o
LEFT JOIN dw.fat_analise_inadimplencia_v4 v4 ON v4.NUM_VENDA = o.NUM_VENDA_FK
WHERE v4.NUM_VENDA IS NULL
GROUP BY o.NUM_VENDA_FK
ORDER BY TOTAL_OCORRENCIAS DESC, o.NUM_VENDA_FK DESC;
