BEGIN TRY
  BEGIN TRAN;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dw.fat_analise_inadimplencia_v4')
      AND name = 'UQ_FAT_INAD_V4_NUM_VENDA'
  )
  BEGIN
    ALTER TABLE dw.fat_analise_inadimplencia_v4
      ADD CONSTRAINT UQ_FAT_INAD_V4_NUM_VENDA UNIQUE (NUM_VENDA);
  END;

  IF EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE parent_object_id = OBJECT_ID('dbo.OCORRENCIAS')
      AND name = 'FK_OCORRENCIAS_FAT_NUMVENDA_V2'
  )
  BEGIN
    ALTER TABLE dbo.OCORRENCIAS
      DROP CONSTRAINT FK_OCORRENCIAS_FAT_NUMVENDA_V2;
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE parent_object_id = OBJECT_ID('dbo.OCORRENCIAS')
      AND name = 'FK_OCORRENCIAS_FAT_NUMVENDA_V4'
  )
  BEGIN
    ALTER TABLE dbo.OCORRENCIAS WITH NOCHECK
      ADD CONSTRAINT FK_OCORRENCIAS_FAT_NUMVENDA_V4
      FOREIGN KEY (NUM_VENDA_FK)
      REFERENCES dw.fat_analise_inadimplencia_v4 (NUM_VENDA);
  END;

  COMMIT TRAN;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
  BEGIN
    ROLLBACK TRAN;
  END;

  THROW;
END CATCH;
