IF OBJECT_ID('dbo.TPROCEDIMENTO_PROVA_QUESTOES', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TPROCEDIMENTO_PROVA_QUESTOES
    (
        ID UNIQUEIDENTIFIER NOT NULL
            CONSTRAINT PK_TPROCEDIMENTO_PROVA_QUESTOES PRIMARY KEY,
        PROCEDIMENTO_ID UNIQUEIDENTIFIER NOT NULL,
        PROCEDIMENTO_VERSAO INT NOT NULL,
        ORDEM INT NOT NULL,
        ENUNCIADO NVARCHAR(2000) NOT NULL,
        PESO DECIMAL(8, 4) NOT NULL
            CONSTRAINT DF_TPROCEDIMENTO_PROVA_QUESTOES_PESO DEFAULT (1),
        CRIADO_EM DATETIME2 NOT NULL
            CONSTRAINT DF_TPROCEDIMENTO_PROVA_QUESTOES_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT CK_TPROCEDIMENTO_PROVA_QUESTOES_VERSAO CHECK (PROCEDIMENTO_VERSAO >= 1),
        CONSTRAINT CK_TPROCEDIMENTO_PROVA_QUESTOES_ORDEM CHECK (ORDEM >= 1),
        CONSTRAINT CK_TPROCEDIMENTO_PROVA_QUESTOES_PESO CHECK (PESO > 0)
    );
END;

IF OBJECT_ID('dbo.TPROCEDIMENTO_PROVA_OPCOES', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TPROCEDIMENTO_PROVA_OPCOES
    (
        ID UNIQUEIDENTIFIER NOT NULL
            CONSTRAINT PK_TPROCEDIMENTO_PROVA_OPCOES PRIMARY KEY,
        QUESTAO_ID UNIQUEIDENTIFIER NOT NULL,
        ORDEM INT NOT NULL,
        TEXTO NVARCHAR(1000) NOT NULL,
        CORRETA BIT NOT NULL,
        CONSTRAINT FK_TPROCEDIMENTO_PROVA_OPCOES_QUESTAO
            FOREIGN KEY (QUESTAO_ID) REFERENCES dbo.TPROCEDIMENTO_PROVA_QUESTOES (ID),
        CONSTRAINT CK_TPROCEDIMENTO_PROVA_OPCOES_ORDEM CHECK (ORDEM >= 1)
    );
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_TPROCEDIMENTO_PROVA_QUESTOES_PROC_VERSAO'
      AND object_id = OBJECT_ID('dbo.TPROCEDIMENTO_PROVA_QUESTOES')
)
BEGIN
    CREATE INDEX IX_TPROCEDIMENTO_PROVA_QUESTOES_PROC_VERSAO
        ON dbo.TPROCEDIMENTO_PROVA_QUESTOES (PROCEDIMENTO_ID, PROCEDIMENTO_VERSAO, ORDEM);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_TPROCEDIMENTO_PROVA_OPCOES_QUESTAO'
      AND object_id = OBJECT_ID('dbo.TPROCEDIMENTO_PROVA_OPCOES')
)
BEGIN
    CREATE INDEX IX_TPROCEDIMENTO_PROVA_OPCOES_QUESTAO
        ON dbo.TPROCEDIMENTO_PROVA_OPCOES (QUESTAO_ID, ORDEM);
END;
