;WITH FACES_DUPLICADAS AS (
    SELECT
        ID,
        ROW_NUMBER() OVER (
            PARTITION BY USUARIO_CPF
            ORDER BY CRIADO_EM DESC, ID DESC
        ) AS RN
    FROM dbo.TUSUARIO_FACES
)
DELETE FROM FACES_DUPLICADAS
WHERE RN > 1;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'UX_TUSUARIO_FACES_CPF'
      AND object_id = OBJECT_ID('dbo.TUSUARIO_FACES')
)
BEGIN
    CREATE UNIQUE INDEX UX_TUSUARIO_FACES_CPF
        ON dbo.TUSUARIO_FACES (USUARIO_CPF);
END;
