IF OBJECT_ID('dbo.TPESQUISA_SATISFACAO_PLATAFORMA', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TPESQUISA_SATISFACAO_PLATAFORMA (
        ID UNIQUEIDENTIFIER NOT NULL
            CONSTRAINT PK_TPESQUISA_SATISFACAO_PLATAFORMA PRIMARY KEY,
        USUARIO_CPF VARCHAR(100) NOT NULL,
        NIVEL_SATISFACAO TINYINT NOT NULL,
        RESPONDIDO_EM DATETIME2 NOT NULL
            CONSTRAINT DF_TPESQUISA_SATISFACAO_PLATAFORMA_RESPONDIDO_EM DEFAULT (SYSUTCDATETIME())
    );
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_TPESQUISA_SATISFACAO_PLATAFORMA_NIVEL'
)
BEGIN
    ALTER TABLE dbo.TPESQUISA_SATISFACAO_PLATAFORMA
        ADD CONSTRAINT CK_TPESQUISA_SATISFACAO_PLATAFORMA_NIVEL
        CHECK (NIVEL_SATISFACAO BETWEEN 1 AND 5);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.TPESQUISA_SATISFACAO_PLATAFORMA')
      AND name = 'IX_TPESQUISA_SATISFACAO_PLATAFORMA_CPF_RESPONDIDO_EM'
)
BEGIN
    CREATE INDEX IX_TPESQUISA_SATISFACAO_PLATAFORMA_CPF_RESPONDIDO_EM
        ON dbo.TPESQUISA_SATISFACAO_PLATAFORMA (USUARIO_CPF, RESPONDIDO_EM DESC);
END;
