/*
  RECRIACAO COMPLETA DO SCHEMA DO MODULO TREINAMENTO (dbo)
  ------------------------------------------------------------------
  - Script consolidado (base + evolucoes/migrations aplicadas)
  - SQL Server (T-SQL / SSMS)
  - ATENCAO: o bloco de DROP apaga todas as tabelas do modulo.

  Observacao importante sobre relacionamentos:
  Algumas colunas sao referencias "logicas" e nao possuem FK fisica por design,
  principalmente em tabelas versionadas/polimorficas:
    - TUSUARIO_TREINAMENTOS (MATERIAL_ID / MATERIAL_VERSAO / TIPO)
    - TVIDEOS/TPDFS/TCANAL_VIDEOS -> NORMA_ID / PROCEDIMENTO_ID
    - TUSUARIO_PROVA_TENTATIVAS -> PROVA_ID / PROVA_VERSAO
    - TPROVA_QUESTOES -> (PROVA_ID, VERSAO)
  Isso evita quebra de historico com o versionamento atual usado pelo sistema.
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

/* ============================================================
   DROP (ORDEM REVERSA DE DEPENDENCIA)
   ============================================================ */
DROP TABLE IF EXISTS dbo.TPESQUISA_SATISFACAO_PLATAFORMA;
DROP TABLE IF EXISTS dbo.TNOTIFICACOES_GESTAO;
DROP TABLE IF EXISTS dbo.TUSUARIO_FACES;
DROP TABLE IF EXISTS dbo.TUSUARIO_PROVA_TENTATIVAS;
DROP TABLE IF EXISTS dbo.TTURMA_EVIDENCIAS;
DROP TABLE IF EXISTS dbo.TTURMA_COLABORADORES;
DROP TABLE IF EXISTS dbo.TUSUARIO_TREINAMENTOS;
DROP TABLE IF EXISTS dbo.TUSUARIO_TRILHAS;
DROP TABLE IF EXISTS dbo.TTURMAS_TREINAMENTO;
DROP TABLE IF EXISTS dbo.TPROVA_OPCOES;
DROP TABLE IF EXISTS dbo.TPROVA_QUESTOES;
DROP TABLE IF EXISTS dbo.TCANAL_VIDEOS;
DROP TABLE IF EXISTS dbo.TPROVAS;
DROP TABLE IF EXISTS dbo.TPDFS;
DROP TABLE IF EXISTS dbo.TVIDEOS;
DROP TABLE IF EXISTS dbo.TNORMAS;
DROP TABLE IF EXISTS dbo.TPROCEDIMENTOS;
DROP TABLE IF EXISTS dbo.TTRILHAS;
DROP TABLE IF EXISTS dbo.TMODULOS;
DROP TABLE IF EXISTS dbo.TMTREINAMENTO;
DROP TABLE IF EXISTS dbo.TUSUARIO_CURSOS;
DROP TABLE IF EXISTS dbo.TCURSOS;
DROP TABLE IF EXISTS dbo.TCANAIS;
DROP TABLE IF EXISTS dbo.TUSUARIOS;
GO

/* ============================================================
   TABELAS BASE
   ============================================================ */

CREATE TABLE dbo.TUSUARIOS (
    CPF VARCHAR(100) NOT NULL
        CONSTRAINT PK_TUSUARIOS PRIMARY KEY,
    NOME VARCHAR(100) NULL,
    IDADE INT NULL,
    SEXO VARCHAR(15) NULL,
    NOMEFILIAL VARCHAR(255) NULL,
    DTNASCIMENTO DATE NULL,
    HASH_SENHA VARCHAR(255) NULL,
    QTD_CURSOS_REALIZADOS INT NOT NULL
        CONSTRAINT DF_TUSUARIOS_QTD_CURSOS_REALIZADOS DEFAULT (0),
    HORAS_CURSOS_REALIZADOS INT NOT NULL
        CONSTRAINT DF_TUSUARIOS_HORAS_CURSOS_REALIZADOS DEFAULT (0),
    CARGO VARCHAR(250) NULL,
    SETOR VARCHAR(255) NULL,
    ATIVO BIT NULL,
    PERMISSAO VARCHAR(255) NULL
        CONSTRAINT DF_TUSUARIOS_PERMISSAO DEFAULT ('usuario'),
    READVIEW_JSON NVARCHAR(MAX) NULL,
    INSTRUTOR BIT NULL
        CONSTRAINT DF_TUSUARIOS_INSTRUTOR DEFAULT (0)
);
GO

CREATE INDEX IX_TUSUARIOS_NOME ON dbo.TUSUARIOS (NOME);
CREATE INDEX IX_TUSUARIOS_INSTRUTOR ON dbo.TUSUARIOS (INSTRUTOR, NOME);
GO

CREATE TABLE dbo.TCURSOS (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TCURSOS PRIMARY KEY,
    TITULO VARCHAR(255) NULL,
    DESCRICAO VARCHAR(255) NULL,
    DURACAO INT NULL,
    MATERIAL_APOIO NVARCHAR(MAX) NULL
);
GO

CREATE TABLE dbo.TMODULOS (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TMODULOS PRIMARY KEY,
    NOME NVARCHAR(255) NOT NULL,
    QTD_TRILHAS INT NOT NULL
        CONSTRAINT DF_TMODULOS_QTD_TRILHAS DEFAULT (0),
    CRIADO_POR NVARCHAR(255) NULL,
    PATH NVARCHAR(500) NULL
);
GO

CREATE INDEX IX_TMODULOS_NOME ON dbo.TMODULOS (NOME);
GO

CREATE TABLE dbo.TCANAIS (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TCANAIS PRIMARY KEY,
    NOME NVARCHAR(255) NOT NULL,
    CRIADO_POR NVARCHAR(255) NULL,
    PATH NVARCHAR(500) NULL,
    CRIADO_EM DATETIME2 NOT NULL
        CONSTRAINT DF_TCANAIS_CRIADO_EM DEFAULT (SYSUTCDATETIME())
);
GO

CREATE INDEX IX_TCANAIS_NOME ON dbo.TCANAIS (NOME);
GO

CREATE TABLE dbo.TMTREINAMENTO (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TMTREINAMENTO PRIMARY KEY,
    CARGO_FK VARCHAR(255) NOT NULL,
    CURSO_ID UNIQUEIDENTIFIER NOT NULL,
    QTD_HORAS INT NULL,
    TITULO VARCHAR(255) NULL,
    PROVA VARBINARY(MAX) NULL,
    CONSTRAINT FK_TMTREINAMENTO_CURSO
        FOREIGN KEY (CURSO_ID) REFERENCES dbo.TCURSOS (ID)
);
GO

CREATE INDEX IX_TMTREINAMENTO_CARGO_FK ON dbo.TMTREINAMENTO (CARGO_FK);
CREATE INDEX IX_TMTREINAMENTO_CURSO_ID ON dbo.TMTREINAMENTO (CURSO_ID);
GO

/* ============================================================
   ESTRUTURA DE TREINAMENTO (MODULO/TRILHA)
   ============================================================ */

CREATE TABLE dbo.TTRILHAS (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TTRILHAS PRIMARY KEY,
    MODULO_FK_ID UNIQUEIDENTIFIER NOT NULL,
    TITULO NVARCHAR(255) NOT NULL,
    CRIADO_POR NVARCHAR(255) NULL,
    ATUALIZADO_EM DATETIME2 NULL,
    PATH NVARCHAR(500) NULL,
    AVALIACAO_EFICACIA_OBRIGATORIA BIT NOT NULL
        CONSTRAINT DF_TTRILHAS_AVALIACAO_EFICACIA_OBRIGATORIA DEFAULT (0),
    AVALIACAO_EFICACIA_PERGUNTA NVARCHAR(MAX) NULL,
    AVALIACAO_EFICACIA_ATUALIZADA_EM DATETIME2 NULL,
    CONSTRAINT FK_TTRILHAS_MODULO
        FOREIGN KEY (MODULO_FK_ID) REFERENCES dbo.TMODULOS (ID)
);
GO

CREATE INDEX IX_TTRILHAS_MODULO_FK_ID ON dbo.TTRILHAS (MODULO_FK_ID);
CREATE INDEX IX_TTRILHAS_TITULO ON dbo.TTRILHAS (TITULO);
GO

/* ============================================================
   TABELAS VERSIONADAS (NORMA / PROCEDIMENTO / MATERIAIS / PROVA)
   ============================================================ */

CREATE TABLE dbo.TPROCEDIMENTOS (
    ID UNIQUEIDENTIFIER NOT NULL,
    NOME NVARCHAR(255) NOT NULL,
    PATH_PDF NVARCHAR(1000) NOT NULL,
    OBSERVACOES NVARCHAR(MAX) NULL,
    VERSAO INT NOT NULL,
    ALTERADO_EM DATETIME2 NOT NULL
        CONSTRAINT DF_TPROCEDIMENTOS_ALTERADO_EM DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT PK_TPROCEDIMENTOS PRIMARY KEY (ID, VERSAO),
    CONSTRAINT CK_TPROCEDIMENTOS_VERSAO CHECK (VERSAO >= 1)
);
GO

CREATE INDEX IX_TPROCEDIMENTOS_ID_VERSAO
    ON dbo.TPROCEDIMENTOS (ID, VERSAO DESC);
CREATE INDEX IX_TPROCEDIMENTOS_NOME
    ON dbo.TPROCEDIMENTOS (NOME);
GO

CREATE TABLE dbo.TNORMAS (
    ID UNIQUEIDENTIFIER NOT NULL,
    NOME NVARCHAR(255) NOT NULL,
    PATH_PDF NVARCHAR(1000) NOT NULL,
    OBSERVACOES NVARCHAR(MAX) NULL,
    VERSAO INT NOT NULL,
    VALIDADE_MESES TINYINT NOT NULL
        CONSTRAINT DF_TNORMAS_VALIDADE_MESES DEFAULT (0),
    VALIDADE_ANOS TINYINT NOT NULL
        CONSTRAINT DF_TNORMAS_VALIDADE_ANOS DEFAULT (0),
    ALTERADO_EM DATETIME2 NOT NULL
        CONSTRAINT DF_TNORMAS_ALTERADO_EM DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT PK_TNORMAS PRIMARY KEY (ID, VERSAO),
    CONSTRAINT CK_TNORMAS_VERSAO CHECK (VERSAO >= 1),
    CONSTRAINT CK_TNORMAS_VALIDADE_MESES CHECK (VALIDADE_MESES BETWEEN 0 AND 11),
    CONSTRAINT CK_TNORMAS_VALIDADE_ANOS CHECK (VALIDADE_ANOS BETWEEN 0 AND 5),
    CONSTRAINT CK_TNORMAS_VALIDADE_TOTAL CHECK ((ISNULL(VALIDADE_ANOS, 0) * 12) + ISNULL(VALIDADE_MESES, 0) > 0)
);
GO

CREATE INDEX IX_TNORMAS_ID_VERSAO
    ON dbo.TNORMAS (ID, VERSAO DESC);
CREATE INDEX IX_TNORMAS_NOME
    ON dbo.TNORMAS (NOME);
GO

CREATE TABLE dbo.TVIDEOS (
    ID UNIQUEIDENTIFIER NOT NULL,
    TRILHA_FK_ID UNIQUEIDENTIFIER NOT NULL,
    PATH_VIDEO NVARCHAR(1000) NOT NULL,
    PROCEDIMENTO_ID UNIQUEIDENTIFIER NULL, -- relacao logica (tabela versionada)
    NORMA_ID UNIQUEIDENTIFIER NULL,        -- relacao logica (tabela versionada)
    DURACAO_SEGUNDOS INT NULL
        CONSTRAINT DF_TVIDEOS_DURACAO_SEGUNDOS DEFAULT (0),
    ORDEM INT NULL,
    VERSAO INT NOT NULL,
    CONSTRAINT PK_TVIDEOS PRIMARY KEY (ID, VERSAO),
    CONSTRAINT FK_TVIDEOS_TRILHA
        FOREIGN KEY (TRILHA_FK_ID) REFERENCES dbo.TTRILHAS (ID),
    CONSTRAINT CK_TVIDEOS_VERSAO CHECK (VERSAO >= 1),
    CONSTRAINT CK_TVIDEOS_DURACAO CHECK (DURACAO_SEGUNDOS IS NULL OR DURACAO_SEGUNDOS >= 0),
    CONSTRAINT CK_TVIDEOS_ORDEM CHECK (ORDEM IS NULL OR ORDEM >= 1)
);
GO

CREATE INDEX IX_TVIDEOS_ID_VERSAO
    ON dbo.TVIDEOS (ID, VERSAO DESC);
CREATE INDEX IX_TVIDEOS_TRILHA_FK_ID
    ON dbo.TVIDEOS (TRILHA_FK_ID, ORDEM, ID, VERSAO DESC);
CREATE INDEX IX_TVIDEOS_NORMA_ID
    ON dbo.TVIDEOS (NORMA_ID)
    INCLUDE (ID, TRILHA_FK_ID, VERSAO);
CREATE INDEX IX_TVIDEOS_PROCEDIMENTO_ID
    ON dbo.TVIDEOS (PROCEDIMENTO_ID)
    INCLUDE (ID, TRILHA_FK_ID, VERSAO);
GO

CREATE TABLE dbo.TPDFS (
    ID UNIQUEIDENTIFIER NOT NULL,
    TRILHA_FK_ID UNIQUEIDENTIFIER NOT NULL,
    PDF_PATH NVARCHAR(1000) NOT NULL,
    PROCEDIMENTO_ID UNIQUEIDENTIFIER NULL, -- relacao logica (tabela versionada)
    NORMA_ID UNIQUEIDENTIFIER NULL,        -- relacao logica (tabela versionada)
    VERSAO INT NOT NULL,
    CONSTRAINT PK_TPDFS PRIMARY KEY (ID, VERSAO),
    CONSTRAINT FK_TPDFS_TRILHA
        FOREIGN KEY (TRILHA_FK_ID) REFERENCES dbo.TTRILHAS (ID),
    CONSTRAINT CK_TPDFS_VERSAO CHECK (VERSAO >= 1)
);
GO

CREATE INDEX IX_TPDFS_ID_VERSAO
    ON dbo.TPDFS (ID, VERSAO DESC);
CREATE INDEX IX_TPDFS_TRILHA_FK_ID
    ON dbo.TPDFS (TRILHA_FK_ID, ID, VERSAO DESC);
CREATE INDEX IX_TPDFS_NORMA_ID
    ON dbo.TPDFS (NORMA_ID)
    INCLUDE (ID, TRILHA_FK_ID, VERSAO);
CREATE INDEX IX_TPDFS_PROCEDIMENTO_ID
    ON dbo.TPDFS (PROCEDIMENTO_ID)
    INCLUDE (ID, TRILHA_FK_ID, VERSAO);
GO

CREATE TABLE dbo.TPROVAS (
    ID UNIQUEIDENTIFIER NOT NULL,
    TRILHA_FK_ID UNIQUEIDENTIFIER NOT NULL,
    PROVA_PATH NVARCHAR(1000) NOT NULL,
    VERSAO INT NOT NULL,
    MODO_APLICACAO VARCHAR(20) NOT NULL
        CONSTRAINT DF_TPROVAS_MODO_APLICACAO DEFAULT ('coletiva'),
    TITULO NVARCHAR(255) NULL,
    NOTA_TOTAL DECIMAL(5, 2) NULL,
    ATUALIZADO_EM DATETIME2 NOT NULL
        CONSTRAINT DF_TPROVAS_ATUALIZADO_EM DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT PK_TPROVAS PRIMARY KEY (ID, VERSAO),
    CONSTRAINT FK_TPROVAS_TRILHA
        FOREIGN KEY (TRILHA_FK_ID) REFERENCES dbo.TTRILHAS (ID),
    CONSTRAINT CK_TPROVAS_VERSAO CHECK (VERSAO >= 1),
    CONSTRAINT CK_TPROVAS_MODO_APLICACAO CHECK (MODO_APLICACAO IN ('coletiva', 'individual')),
    CONSTRAINT CK_TPROVAS_NOTA_TOTAL CHECK (NOTA_TOTAL IS NULL OR NOTA_TOTAL >= 0)
);
GO

CREATE INDEX IX_TPROVAS_ID_VERSAO
    ON dbo.TPROVAS (ID, VERSAO DESC);
CREATE INDEX IX_TPROVAS_TRILHA_FK_ID
    ON dbo.TPROVAS (TRILHA_FK_ID, VERSAO DESC);
CREATE INDEX IX_TPROVAS_TRILHA_PATH
    ON dbo.TPROVAS (TRILHA_FK_ID, PROVA_PATH, VERSAO DESC);
GO

CREATE TABLE dbo.TPROVA_QUESTOES (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TPROVA_QUESTOES PRIMARY KEY,
    PROVA_ID UNIQUEIDENTIFIER NOT NULL, -- relacao logica com TPROVAS (versionada)
    VERSAO INT NOT NULL,
    ORDEM INT NOT NULL,
    ENUNCIADO NVARCHAR(2000) NOT NULL,
    PESO DECIMAL(5, 2) NOT NULL,
    CONSTRAINT CK_TPROVA_QUESTOES_VERSAO CHECK (VERSAO >= 1),
    CONSTRAINT CK_TPROVA_QUESTOES_ORDEM CHECK (ORDEM >= 1),
    CONSTRAINT CK_TPROVA_QUESTOES_PESO CHECK (PESO > 0)
);
GO

CREATE INDEX IX_TPROVA_QUESTOES_PROVA_VERSAO
    ON dbo.TPROVA_QUESTOES (PROVA_ID, VERSAO, ORDEM);
GO

CREATE TABLE dbo.TPROVA_OPCOES (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TPROVA_OPCOES PRIMARY KEY,
    QUESTAO_ID UNIQUEIDENTIFIER NOT NULL,
    ORDEM INT NOT NULL,
    TEXTO NVARCHAR(1000) NOT NULL,
    CORRETA BIT NOT NULL,
    CONSTRAINT FK_TPROVA_OPCOES_QUESTAO
        FOREIGN KEY (QUESTAO_ID) REFERENCES dbo.TPROVA_QUESTOES (ID),
    CONSTRAINT CK_TPROVA_OPCOES_ORDEM CHECK (ORDEM >= 1)
);
GO

CREATE INDEX IX_TPROVA_OPCOES_QUESTAO
    ON dbo.TPROVA_OPCOES (QUESTAO_ID, ORDEM);
GO

CREATE TABLE dbo.TCANAL_VIDEOS (
    ID UNIQUEIDENTIFIER NOT NULL,
    CANAL_FK_ID UNIQUEIDENTIFIER NOT NULL,
    PATH_VIDEO NVARCHAR(1000) NOT NULL,
    TIPO_CONTEUDO VARCHAR(20) NOT NULL
        CONSTRAINT DF_TCANAL_VIDEOS_TIPO_CONTEUDO DEFAULT ('video'),
    PROCEDIMENTO_ID UNIQUEIDENTIFIER NULL, -- relacao logica (tabela versionada)
    NORMA_ID UNIQUEIDENTIFIER NULL,        -- relacao logica (tabela versionada)
    DURACAO_SEGUNDOS INT NULL
        CONSTRAINT DF_TCANAL_VIDEOS_DURACAO_SEGUNDOS DEFAULT (0),
    VERSAO INT NOT NULL,
    CONSTRAINT PK_TCANAL_VIDEOS PRIMARY KEY (ID, VERSAO),
    CONSTRAINT FK_TCANAL_VIDEOS_CANAL
        FOREIGN KEY (CANAL_FK_ID) REFERENCES dbo.TCANAIS (ID),
    CONSTRAINT CK_TCANAL_VIDEOS_VERSAO CHECK (VERSAO >= 1),
    CONSTRAINT CK_TCANAL_VIDEOS_TIPO_CONTEUDO CHECK (TIPO_CONTEUDO IN ('video', 'pdf')),
    CONSTRAINT CK_TCANAL_VIDEOS_DURACAO CHECK (DURACAO_SEGUNDOS IS NULL OR DURACAO_SEGUNDOS >= 0)
);
GO

CREATE INDEX IX_TCANAL_VIDEOS_ID_VERSAO
    ON dbo.TCANAL_VIDEOS (ID, VERSAO DESC);
CREATE INDEX IX_TCANAL_VIDEOS_CANAL_FK_ID
    ON dbo.TCANAL_VIDEOS (CANAL_FK_ID, TIPO_CONTEUDO, ID, VERSAO DESC);
CREATE INDEX IX_TCANAL_VIDEOS_PROCEDIMENTO_ID
    ON dbo.TCANAL_VIDEOS (PROCEDIMENTO_ID)
    INCLUDE (ID, CANAL_FK_ID, VERSAO, TIPO_CONTEUDO);
CREATE INDEX IX_TCANAL_VIDEOS_NORMA_ID
    ON dbo.TCANAL_VIDEOS (NORMA_ID)
    INCLUDE (ID, CANAL_FK_ID, VERSAO, TIPO_CONTEUDO);
GO

/* ============================================================
   TURMAS / COLETIVO
   ============================================================ */

CREATE TABLE dbo.TTURMAS_TREINAMENTO (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TTURMAS_TREINAMENTO PRIMARY KEY,
    NOME NVARCHAR(200) NOT NULL,
    STATUS VARCHAR(30) NOT NULL
        CONSTRAINT DF_TTURMAS_TREINAMENTO_STATUS DEFAULT ('iniciada'),
    CRIADO_POR VARCHAR(100) NULL,
    CRIADO_EM DATETIME2 NOT NULL
        CONSTRAINT DF_TTURMAS_TREINAMENTO_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
    INICIADO_EM DATETIME2 NULL,
    FINALIZADO_EM DATETIME2 NULL,
    DURACAO_TREINAMENTO_MINUTOS INT NULL,
    CONSTRAINT CK_TTURMAS_TREINAMENTO_DURACAO CHECK (DURACAO_TREINAMENTO_MINUTOS IS NULL OR DURACAO_TREINAMENTO_MINUTOS >= 0)
    -- STATUS mantido sem CHECK fechado para compatibilidade com futuros estados
);
GO

CREATE INDEX IX_TTURMAS_TREINAMENTO_CRIADO_EM
    ON dbo.TTURMAS_TREINAMENTO (CRIADO_EM DESC);
CREATE INDEX IX_TTURMAS_TREINAMENTO_STATUS
    ON dbo.TTURMAS_TREINAMENTO (STATUS, CRIADO_EM DESC);
GO

CREATE TABLE dbo.TTURMA_COLABORADORES (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TTURMA_COLABORADORES PRIMARY KEY,
    TURMA_ID UNIQUEIDENTIFIER NOT NULL,
    USUARIO_CPF VARCHAR(100) NOT NULL,
    CRIADO_EM DATETIME2 NOT NULL
        CONSTRAINT DF_TTURMA_COLABORADORES_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT FK_TTURMA_COLABORADORES_TURMA
        FOREIGN KEY (TURMA_ID) REFERENCES dbo.TTURMAS_TREINAMENTO (ID),
    CONSTRAINT FK_TTURMA_COLABORADORES_USUARIO
        FOREIGN KEY (USUARIO_CPF) REFERENCES dbo.TUSUARIOS (CPF)
);
GO

CREATE UNIQUE INDEX UX_TTURMA_COLABORADORES_TURMA_CPF
    ON dbo.TTURMA_COLABORADORES (TURMA_ID, USUARIO_CPF);
CREATE INDEX IX_TTURMA_COLABORADORES_CPF
    ON dbo.TTURMA_COLABORADORES (USUARIO_CPF);
GO

CREATE TABLE dbo.TTURMA_EVIDENCIAS (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TTURMA_EVIDENCIAS PRIMARY KEY,
    TURMA_ID UNIQUEIDENTIFIER NOT NULL,
    ARQUIVO_PATH NVARCHAR(1000) NOT NULL,
    CRIADO_POR VARCHAR(100) NULL,
    CRIADO_EM DATETIME2 NOT NULL
        CONSTRAINT DF_TTURMA_EVIDENCIAS_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
    ORDEM INT NOT NULL
        CONSTRAINT DF_TTURMA_EVIDENCIAS_ORDEM DEFAULT (1),
    CONSTRAINT FK_TTURMA_EVIDENCIAS_TURMA
        FOREIGN KEY (TURMA_ID) REFERENCES dbo.TTURMAS_TREINAMENTO (ID),
    CONSTRAINT CK_TTURMA_EVIDENCIAS_ORDEM CHECK (ORDEM >= 1)
);
GO

CREATE INDEX IX_TTURMA_EVIDENCIAS_TURMA_ID
    ON dbo.TTURMA_EVIDENCIAS (TURMA_ID, ORDEM, CRIADO_EM);
GO

/* ============================================================
   VINCULOS E REGISTROS DE USUARIO
   ============================================================ */

CREATE TABLE dbo.TUSUARIO_TRILHAS (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TUSUARIO_TRILHAS PRIMARY KEY,
    USUARIO_CPF VARCHAR(100) NOT NULL,
    TRILHA_ID UNIQUEIDENTIFIER NOT NULL,
    DT_ATRIBUICAO DATETIME2 NOT NULL
        CONSTRAINT DF_TUSUARIO_TRILHAS_DT_ATRIBUICAO DEFAULT (SYSUTCDATETIME()),
    ATRIBUIDO_POR VARCHAR(100) NULL,
    CONSTRAINT FK_TUSUARIO_TRILHAS_USUARIO
        FOREIGN KEY (USUARIO_CPF) REFERENCES dbo.TUSUARIOS (CPF),
    CONSTRAINT FK_TUSUARIO_TRILHAS_TRILHA
        FOREIGN KEY (TRILHA_ID) REFERENCES dbo.TTRILHAS (ID)
);
GO

CREATE UNIQUE INDEX UX_TUSUARIO_TRILHAS_USUARIO_TRILHA
    ON dbo.TUSUARIO_TRILHAS (USUARIO_CPF, TRILHA_ID);
CREATE INDEX IX_TUSUARIO_TRILHAS_TRILHA_ID
    ON dbo.TUSUARIO_TRILHAS (TRILHA_ID);
GO

CREATE TABLE dbo.TUSUARIO_TREINAMENTOS (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TUSUARIO_TREINAMENTOS PRIMARY KEY,
    USUARIO_CPF VARCHAR(100) NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    MATERIAL_ID UNIQUEIDENTIFIER NOT NULL,
    MATERIAL_VERSAO INT NULL,
    TURMA_ID UNIQUEIDENTIFIER NULL,
    DT_CONCLUSAO DATETIME2 NOT NULL,
    ORIGEM VARCHAR(50) NULL,
    ARQUIVADO_EM DATETIME2 NULL,
    FACE_CONFIRMACAO_FOTO_BASE64 NVARCHAR(MAX) NULL,
    FACE_CONFIRMACAO_FOTO_URL NVARCHAR(2000) NULL,
    FACE_CONFIRMACAO_EM DATETIME2 NULL,
    AVALIACAO_EFICACIA_NIVEL TINYINT NULL,
    AVALIACAO_EFICACIA_EM DATETIME2 NULL,
    CONSTRAINT FK_TUSUARIO_TREINAMENTOS_USUARIO
        FOREIGN KEY (USUARIO_CPF) REFERENCES dbo.TUSUARIOS (CPF),
    CONSTRAINT FK_TUSUARIO_TREINAMENTOS_TURMA
        FOREIGN KEY (TURMA_ID) REFERENCES dbo.TTURMAS_TREINAMENTO (ID),
    CONSTRAINT CK_TUSUARIO_TREINAMENTOS_TIPO CHECK (TIPO IN ('video', 'pdf', 'prova')),
    CONSTRAINT CK_TUSUARIO_TREINAMENTOS_AVALIACAO_EFICACIA_NIVEL CHECK (
        AVALIACAO_EFICACIA_NIVEL IS NULL OR AVALIACAO_EFICACIA_NIVEL BETWEEN 1 AND 5
    )
);
GO

CREATE UNIQUE INDEX UX_TUSUARIO_TREINAMENTOS
    ON dbo.TUSUARIO_TREINAMENTOS (USUARIO_CPF, TIPO, MATERIAL_ID, MATERIAL_VERSAO);
CREATE INDEX IX_TUSUARIO_TREINAMENTOS_USUARIO_TIPO
    ON dbo.TUSUARIO_TREINAMENTOS (USUARIO_CPF, TIPO, ARQUIVADO_EM, DT_CONCLUSAO DESC);
CREATE INDEX IX_TUSUARIO_TREINAMENTOS_MATERIAL
    ON dbo.TUSUARIO_TREINAMENTOS (TIPO, MATERIAL_ID, MATERIAL_VERSAO, ARQUIVADO_EM);
CREATE INDEX IX_TUSUARIO_TREINAMENTOS_TURMA_ID
    ON dbo.TUSUARIO_TREINAMENTOS (TURMA_ID);
CREATE INDEX IX_TUSUARIO_TREINAMENTOS_DTCONCLUSAO
    ON dbo.TUSUARIO_TREINAMENTOS (DT_CONCLUSAO DESC);
GO

CREATE TABLE dbo.TUSUARIO_PROVA_TENTATIVAS (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TUSUARIO_PROVA_TENTATIVAS PRIMARY KEY,
    USUARIO_CPF VARCHAR(100) NOT NULL,
    PROVA_ID UNIQUEIDENTIFIER NOT NULL,   -- relacao logica com TPROVAS (versionada)
    PROVA_VERSAO INT NOT NULL,
    TRILHA_ID UNIQUEIDENTIFIER NOT NULL,
    NOTA DECIMAL(5, 2) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    ACERTOS INT NOT NULL,
    TOTAL_QUESTOES INT NOT NULL,
    RESPOSTAS_JSON NVARCHAR(MAX) NULL,
    DT_REALIZACAO DATETIME2 NOT NULL
        CONSTRAINT DF_TUSUARIO_PROVA_TENTATIVAS_DT_REALIZACAO DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT FK_TUSUARIO_PROVA_TENTATIVAS_USUARIO
        FOREIGN KEY (USUARIO_CPF) REFERENCES dbo.TUSUARIOS (CPF),
    CONSTRAINT FK_TUSUARIO_PROVA_TENTATIVAS_TRILHA
        FOREIGN KEY (TRILHA_ID) REFERENCES dbo.TTRILHAS (ID),
    CONSTRAINT CK_TUSUARIO_PROVA_TENTATIVAS_STATUS CHECK (STATUS IN ('aprovado', 'reprovado')),
    CONSTRAINT CK_TUSUARIO_PROVA_TENTATIVAS_NOTA CHECK (NOTA >= 0),
    CONSTRAINT CK_TUSUARIO_PROVA_TENTATIVAS_ACERTOS CHECK (ACERTOS >= 0),
    CONSTRAINT CK_TUSUARIO_PROVA_TENTATIVAS_TOTAL_QUESTOES CHECK (TOTAL_QUESTOES >= 0)
);
GO

CREATE INDEX IX_TUSUARIO_PROVA_TENTATIVAS_USUARIO_TRILHA_DATA
    ON dbo.TUSUARIO_PROVA_TENTATIVAS (USUARIO_CPF, TRILHA_ID, DT_REALIZACAO DESC);
CREATE INDEX IX_TUSUARIO_PROVA_TENTATIVAS_TRILHA_DATA
    ON dbo.TUSUARIO_PROVA_TENTATIVAS (TRILHA_ID, DT_REALIZACAO DESC);
CREATE INDEX IX_TUSUARIO_PROVA_TENTATIVAS_PROVA
    ON dbo.TUSUARIO_PROVA_TENTATIVAS (PROVA_ID, PROVA_VERSAO, DT_REALIZACAO DESC);
GO

CREATE TABLE dbo.TUSUARIO_FACES (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TUSUARIO_FACES PRIMARY KEY,
    USUARIO_CPF VARCHAR(100) NOT NULL,
    DESCRIPTOR_JSON NVARCHAR(MAX) NOT NULL,
    FOTO_BASE64 NVARCHAR(MAX) NULL,
    FOTO_URL NVARCHAR(2000) NULL,
    ORIGEM VARCHAR(50) NULL,
    CRIADO_POR VARCHAR(100) NULL,
    CRIADO_EM DATETIME2 NOT NULL
        CONSTRAINT DF_TUSUARIO_FACES_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT FK_TUSUARIO_FACES_USUARIO
        FOREIGN KEY (USUARIO_CPF) REFERENCES dbo.TUSUARIOS (CPF)
);
GO

CREATE INDEX IX_TUSUARIO_FACES_CPF_CRIADO_EM
    ON dbo.TUSUARIO_FACES (USUARIO_CPF, CRIADO_EM DESC);
CREATE INDEX IX_TUSUARIO_FACES_CRIADO_EM
    ON dbo.TUSUARIO_FACES (CRIADO_EM DESC);
CREATE UNIQUE INDEX UX_TUSUARIO_FACES_CPF
    ON dbo.TUSUARIO_FACES (USUARIO_CPF);
GO

CREATE TABLE dbo.TUSUARIO_CURSOS (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TUSUARIO_CURSOS PRIMARY KEY,
    USUARIO_CPF VARCHAR(100) NOT NULL,
    CURSO_ID UNIQUEIDENTIFIER NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    DT_INICIO DATE NULL,
    DT_CONCLUSAO DATE NULL,
    CONSTRAINT FK_TUSUARIO_CURSOS_USUARIO
        FOREIGN KEY (USUARIO_CPF) REFERENCES dbo.TUSUARIOS (CPF),
    CONSTRAINT FK_TUSUARIO_CURSOS_CURSO
        FOREIGN KEY (CURSO_ID) REFERENCES dbo.TCURSOS (ID)
);
GO

CREATE INDEX IX_TUSUARIO_CURSOS_USUARIO
    ON dbo.TUSUARIO_CURSOS (USUARIO_CPF, STATUS);
CREATE INDEX IX_TUSUARIO_CURSOS_CURSO
    ON dbo.TUSUARIO_CURSOS (CURSO_ID);
GO

/* ============================================================
   NOTIFICACOES / FEEDBACKS
   ============================================================ */

CREATE TABLE dbo.TNOTIFICACOES_GESTAO (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TNOTIFICACOES_GESTAO PRIMARY KEY,
    USUARIO_CPF VARCHAR(100) NOT NULL,
    TIPO_MATERIAL VARCHAR(20) NOT NULL,
    MATERIAL_ID UNIQUEIDENTIFIER NOT NULL,
    MATERIAL_VERSAO INT NULL,
    NORMA_ID UNIQUEIDENTIFIER NOT NULL, -- relacao logica (tabela versionada)
    TRILHA_ID UNIQUEIDENTIFIER NULL,    -- relacao logica para manter historico flexivel
    DT_CONCLUSAO DATETIME2 NOT NULL,
    VENCE_EM DATETIME2 NOT NULL,
    CRIADO_EM DATETIME2 NOT NULL
        CONSTRAINT DF_TNOTIFICACOES_GESTAO_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
    LIDA_EM DATETIME2 NULL,
    CONSTRAINT CK_TNOTIFICACOES_GESTAO_TIPO CHECK (TIPO_MATERIAL IN ('video', 'pdf'))
);
GO

CREATE INDEX IX_TNOTIFICACOES_GESTAO_STATUS
    ON dbo.TNOTIFICACOES_GESTAO (LIDA_EM, VENCE_EM, CRIADO_EM DESC);
CREATE INDEX IX_TNOTIFICACOES_GESTAO_USUARIO
    ON dbo.TNOTIFICACOES_GESTAO (USUARIO_CPF, VENCE_EM DESC);
CREATE INDEX IX_TNOTIFICACOES_GESTAO_MATERIAL
    ON dbo.TNOTIFICACOES_GESTAO (TIPO_MATERIAL, MATERIAL_ID, MATERIAL_VERSAO, VENCE_EM);
GO

CREATE TABLE dbo.TPESQUISA_SATISFACAO_PLATAFORMA (
    ID UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_TPESQUISA_SATISFACAO_PLATAFORMA PRIMARY KEY,
    USUARIO_CPF VARCHAR(100) NOT NULL,
    NIVEL_SATISFACAO TINYINT NOT NULL,
    RESPONDIDO_EM DATETIME2 NOT NULL
        CONSTRAINT DF_TPESQUISA_SATISFACAO_PLATAFORMA_RESPONDIDO_EM DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT CK_TPESQUISA_SATISFACAO_PLATAFORMA_NIVEL CHECK (NIVEL_SATISFACAO BETWEEN 1 AND 5)
    -- sem FK para TUSUARIOS para manter historico mesmo se cadastro local nao existir
);
GO

CREATE INDEX IX_TPESQUISA_SATISFACAO_PLATAFORMA_CPF_RESPONDIDO_EM
    ON dbo.TPESQUISA_SATISFACAO_PLATAFORMA (USUARIO_CPF, RESPONDIDO_EM DESC);
GO

/* ============================================================
   VALIDACAO RAPIDA (OPCIONAL)
   ============================================================ */
-- SELECT name FROM sys.tables WHERE name LIKE 'T%' ORDER BY name;
GO
