IF OBJECT_ID('dbo.TNORMAS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TNORMAS (
        ID UNIQUEIDENTIFIER NOT NULL,
        NOME NVARCHAR(255) NOT NULL,
        PATH_PDF NVARCHAR(1000) NOT NULL,
        VERSAO INT NOT NULL,
        VALIDADE_MESES TINYINT NOT NULL
            CONSTRAINT DF_TNORMAS_VALIDADE_MESES DEFAULT (0),
        VALIDADE_ANOS TINYINT NOT NULL
            CONSTRAINT DF_TNORMAS_VALIDADE_ANOS DEFAULT (0),
        ALTERADO_EM DATETIME2 NOT NULL
            CONSTRAINT DF_TNORMAS_ALTERADO_EM DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_TNORMAS PRIMARY KEY (ID, VERSAO)
    );
END;

IF COL_LENGTH('dbo.TNORMAS', 'VALIDADE_MESES') IS NULL
BEGIN
    ALTER TABLE dbo.TNORMAS
        ADD VALIDADE_MESES TINYINT NOT NULL
            CONSTRAINT DF_TNORMAS_VALIDADE_MESES DEFAULT (0);
END;

IF COL_LENGTH('dbo.TNORMAS', 'VALIDADE_ANOS') IS NULL
BEGIN
    ALTER TABLE dbo.TNORMAS
        ADD VALIDADE_ANOS TINYINT NOT NULL
            CONSTRAINT DF_TNORMAS_VALIDADE_ANOS DEFAULT (0);
END;

DECLARE @defaultValidadeAnos SYSNAME;
SELECT @defaultValidadeAnos = dc.name
FROM sys.default_constraints dc
INNER JOIN sys.columns c
    ON c.default_object_id = dc.object_id
WHERE dc.parent_object_id = OBJECT_ID('dbo.TNORMAS')
  AND c.name = 'VALIDADE_ANOS';

IF @defaultValidadeAnos IS NOT NULL
BEGIN
    DECLARE @dropDefaultValidadeAnos NVARCHAR(MAX) =
        N'ALTER TABLE dbo.TNORMAS DROP CONSTRAINT ' + QUOTENAME(@defaultValidadeAnos) + N';';
    EXEC sp_executesql @dropDefaultValidadeAnos;
END;

ALTER TABLE dbo.TNORMAS
    ADD CONSTRAINT DF_TNORMAS_VALIDADE_ANOS DEFAULT (0) FOR VALIDADE_ANOS;

IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_TNORMAS_VALIDADE_MESES'
      AND parent_object_id = OBJECT_ID('dbo.TNORMAS')
)
BEGIN
    ALTER TABLE dbo.TNORMAS
        ADD CONSTRAINT CK_TNORMAS_VALIDADE_MESES
            CHECK (VALIDADE_MESES BETWEEN 0 AND 11);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_TNORMAS_VALIDADE_ANOS'
      AND parent_object_id = OBJECT_ID('dbo.TNORMAS')
)
BEGIN
    ALTER TABLE dbo.TNORMAS
        ADD CONSTRAINT CK_TNORMAS_VALIDADE_ANOS
            CHECK (VALIDADE_ANOS BETWEEN 0 AND 5);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_TNORMAS_VALIDADE_TOTAL'
      AND parent_object_id = OBJECT_ID('dbo.TNORMAS')
)
BEGIN
    ALTER TABLE dbo.TNORMAS
        ADD CONSTRAINT CK_TNORMAS_VALIDADE_TOTAL
            CHECK ((ISNULL(VALIDADE_ANOS, 0) * 12) + ISNULL(VALIDADE_MESES, 0) > 0);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_TNORMAS_ID_VERSAO'
      AND object_id = OBJECT_ID('dbo.TNORMAS')
)
BEGIN
    CREATE INDEX IX_TNORMAS_ID_VERSAO
        ON dbo.TNORMAS (ID, VERSAO DESC);
END;
