IF COL_LENGTH('dbo.TUSUARIO_TREINAMENTOS', 'AVALIACAO_EFICACIA_NIVEL') IS NULL
BEGIN
    ALTER TABLE dbo.TUSUARIO_TREINAMENTOS
        ADD AVALIACAO_EFICACIA_NIVEL TINYINT NULL;
END;

IF COL_LENGTH('dbo.TUSUARIO_TREINAMENTOS', 'AVALIACAO_EFICACIA_EM') IS NULL
BEGIN
    ALTER TABLE dbo.TUSUARIO_TREINAMENTOS
        ADD AVALIACAO_EFICACIA_EM DATETIME2 NULL;
END;
