IF OBJECT_ID('dbo.TGESTAO_ARQUIVOS_SETOR_COMPARTILHAMENTOS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.TGESTAO_ARQUIVOS_SETOR_COMPARTILHAMENTOS (
    ID UNIQUEIDENTIFIER NOT NULL
      CONSTRAINT PK_TGESTAO_ARQUIVOS_SETOR_COMPARTILHAMENTOS PRIMARY KEY,
    SHAREPOINT_ITEM_ID NVARCHAR(255) NOT NULL,
    SETOR_ORIGEM_CHAVE NVARCHAR(120) NOT NULL,
    SETOR_DESTINO_CHAVE NVARCHAR(120) NOT NULL,
    COMPARTILHADO_POR_NOME NVARCHAR(255) NULL,
    COMPARTILHADO_POR_EMAIL NVARCHAR(255) NULL,
    COMPARTILHADO_POR_USUARIO NVARCHAR(255) NULL,
    COMPARTILHADO_EM DATETIME2(0) NOT NULL
      CONSTRAINT DF_TGESTAO_ARQUIVOS_SETOR_COMPART_EM DEFAULT SYSUTCDATETIME()
  )

  CREATE UNIQUE INDEX UX_TGESTAO_ARQUIVOS_SETOR_COMPART_ITEM_DESTINO
    ON dbo.TGESTAO_ARQUIVOS_SETOR_COMPARTILHAMENTOS (SHAREPOINT_ITEM_ID, SETOR_DESTINO_CHAVE)

  CREATE INDEX IX_TGESTAO_ARQUIVOS_SETOR_COMPART_DESTINO
    ON dbo.TGESTAO_ARQUIVOS_SETOR_COMPARTILHAMENTOS (SETOR_DESTINO_CHAVE, COMPARTILHADO_EM)

  CREATE INDEX IX_TGESTAO_ARQUIVOS_SETOR_COMPART_ORIGEM
    ON dbo.TGESTAO_ARQUIVOS_SETOR_COMPARTILHAMENTOS (SETOR_ORIGEM_CHAVE, SHAREPOINT_ITEM_ID)
END
