IF COL_LENGTH('dbo.TTURMAS_TREINAMENTO', 'DURACAO_TREINAMENTO_MINUTOS') IS NULL
BEGIN
    ALTER TABLE dbo.TTURMAS_TREINAMENTO
        ADD DURACAO_TREINAMENTO_MINUTOS INT NULL;
END;

IF OBJECT_ID('dbo.TTURMA_EVIDENCIAS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TTURMA_EVIDENCIAS
    (
        ID UNIQUEIDENTIFIER NOT NULL
            CONSTRAINT PK_TTURMA_EVIDENCIAS PRIMARY KEY,
        TURMA_ID UNIQUEIDENTIFIER NOT NULL,
        ARQUIVO_PATH NVARCHAR(1000) NOT NULL,
        CRIADO_POR VARCHAR(100) NULL,
        CRIADO_EM DATETIME2 NOT NULL
            CONSTRAINT DF_TTURMA_EVIDENCIAS_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        ORDEM INT NOT NULL
            CONSTRAINT DF_TTURMA_EVIDENCIAS_ORDEM DEFAULT (1)
    );

    ALTER TABLE dbo.TTURMA_EVIDENCIAS
        ADD CONSTRAINT FK_TTURMA_EVIDENCIAS_TURMA
            FOREIGN KEY (TURMA_ID) REFERENCES dbo.TTURMAS_TREINAMENTO (ID);

    CREATE INDEX IX_TTURMA_EVIDENCIAS_TURMA_ID
        ON dbo.TTURMA_EVIDENCIAS (TURMA_ID, ORDEM, CRIADO_EM);
END;
