IF OBJECT_ID('dbo.TTURMAS_TREINAMENTO', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TTURMAS_TREINAMENTO (
        ID UNIQUEIDENTIFIER NOT NULL,
        NOME NVARCHAR(200) NOT NULL,
        STATUS VARCHAR(30) NOT NULL
            CONSTRAINT DF_TTURMAS_TREINAMENTO_STATUS DEFAULT 'iniciada',
        CRIADO_POR VARCHAR(100) NULL,
        CRIADO_EM DATETIME2 NOT NULL
            CONSTRAINT DF_TTURMAS_TREINAMENTO_CRIADO_EM DEFAULT SYSUTCDATETIME(),
        INICIADO_EM DATETIME2 NULL,
        FINALIZADO_EM DATETIME2 NULL,
        CONSTRAINT PK_TTURMAS_TREINAMENTO PRIMARY KEY (ID)
    );
END;

IF OBJECT_ID('dbo.TTURMA_COLABORADORES', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TTURMA_COLABORADORES (
        ID UNIQUEIDENTIFIER NOT NULL,
        TURMA_ID UNIQUEIDENTIFIER NOT NULL,
        USUARIO_CPF VARCHAR(100) NOT NULL,
        CRIADO_EM DATETIME2 NOT NULL
            CONSTRAINT DF_TTURMA_COLABORADORES_CRIADO_EM DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_TTURMA_COLABORADORES PRIMARY KEY (ID),
        CONSTRAINT FK_TTURMA_COLABORADORES_TURMA
            FOREIGN KEY (TURMA_ID) REFERENCES dbo.TTURMAS_TREINAMENTO (ID),
        CONSTRAINT FK_TTURMA_COLABORADORES_USUARIO
            FOREIGN KEY (USUARIO_CPF) REFERENCES dbo.TUSUARIOS (CPF)
    );
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'UX_TTURMA_COLABORADORES_TURMA_CPF'
      AND object_id = OBJECT_ID('dbo.TTURMA_COLABORADORES')
)
BEGIN
    CREATE UNIQUE INDEX UX_TTURMA_COLABORADORES_TURMA_CPF
        ON dbo.TTURMA_COLABORADORES (TURMA_ID, USUARIO_CPF);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_TTURMA_COLABORADORES_CPF'
      AND object_id = OBJECT_ID('dbo.TTURMA_COLABORADORES')
)
BEGIN
    CREATE INDEX IX_TTURMA_COLABORADORES_CPF
        ON dbo.TTURMA_COLABORADORES (USUARIO_CPF);
END;

IF COL_LENGTH('dbo.TUSUARIO_TREINAMENTOS', 'TURMA_ID') IS NULL
BEGIN
    ALTER TABLE dbo.TUSUARIO_TREINAMENTOS
        ADD TURMA_ID UNIQUEIDENTIFIER NULL;
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_TUSUARIO_TREINAMENTOS_TURMA'
)
BEGIN
    ALTER TABLE dbo.TUSUARIO_TREINAMENTOS
        ADD CONSTRAINT FK_TUSUARIO_TREINAMENTOS_TURMA
            FOREIGN KEY (TURMA_ID) REFERENCES dbo.TTURMAS_TREINAMENTO (ID);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_TUSUARIO_TREINAMENTOS_TURMA_ID'
      AND object_id = OBJECT_ID('dbo.TUSUARIO_TREINAMENTOS')
)
BEGIN
    CREATE INDEX IX_TUSUARIO_TREINAMENTOS_TURMA_ID
        ON dbo.TUSUARIO_TREINAMENTOS (TURMA_ID);
END;
