IF COL_LENGTH('dbo.TUSUARIO_FACES', 'FOTO_URL') IS NULL
BEGIN
    ALTER TABLE dbo.TUSUARIO_FACES
        ADD FOTO_URL NVARCHAR(2000) NULL;
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_TUSUARIO_FACES_CRIADO_EM'
      AND object_id = OBJECT_ID('dbo.TUSUARIO_FACES')
)
BEGIN
    CREATE INDEX IX_TUSUARIO_FACES_CRIADO_EM
        ON dbo.TUSUARIO_FACES (CRIADO_EM DESC);
END;
