IF OBJECT_ID('dbo.TGESTAO_ARQUIVOS_SETOR_PASTAS', 'U') IS NOT NULL
BEGIN
  IF COL_LENGTH('dbo.TGESTAO_ARQUIVOS_SETOR_PASTAS', 'VALIDADE_MESES') IS NULL
  BEGIN
    EXEC('ALTER TABLE dbo.TGESTAO_ARQUIVOS_SETOR_PASTAS ADD VALIDADE_MESES TINYINT NULL')
  END

  IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_TGESTAO_ARQUIVOS_SETOR_PASTAS_VALIDADE_MESES'
  )
  BEGIN
    EXEC('
      ALTER TABLE dbo.TGESTAO_ARQUIVOS_SETOR_PASTAS
      ADD CONSTRAINT CK_TGESTAO_ARQUIVOS_SETOR_PASTAS_VALIDADE_MESES
      CHECK (VALIDADE_MESES IS NULL OR VALIDADE_MESES BETWEEN 1 AND 11)
    ')
  END

  IF COL_LENGTH('dbo.TGESTAO_ARQUIVOS_SETOR_PASTAS', 'VALIDADE_ANOS') IS NULL
  BEGIN
    EXEC('ALTER TABLE dbo.TGESTAO_ARQUIVOS_SETOR_PASTAS ADD VALIDADE_ANOS TINYINT NULL')
  END

  IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_TGESTAO_ARQUIVOS_SETOR_PASTAS_VALIDADE_ANOS'
  )
  BEGIN
    EXEC('
      ALTER TABLE dbo.TGESTAO_ARQUIVOS_SETOR_PASTAS
      ADD CONSTRAINT CK_TGESTAO_ARQUIVOS_SETOR_PASTAS_VALIDADE_ANOS
      CHECK (VALIDADE_ANOS IS NULL OR VALIDADE_ANOS BETWEEN 1 AND 3)
    ')
  END
END
