IF COL_LENGTH('dbo.TTRILHAS', 'AVALIACAO_EFICACIA_OBRIGATORIA') IS NULL
BEGIN
    ALTER TABLE dbo.TTRILHAS
        ADD AVALIACAO_EFICACIA_OBRIGATORIA BIT NOT NULL
            CONSTRAINT DF_TTRILHAS_AVALIACAO_EFICACIA_OBRIGATORIA DEFAULT (0);
END;

IF COL_LENGTH('dbo.TTRILHAS', 'AVALIACAO_EFICACIA_PERGUNTA') IS NULL
BEGIN
    ALTER TABLE dbo.TTRILHAS
        ADD AVALIACAO_EFICACIA_PERGUNTA NVARCHAR(MAX) NULL;
END;

IF COL_LENGTH('dbo.TTRILHAS', 'AVALIACAO_EFICACIA_ATUALIZADA_EM') IS NULL
BEGIN
    ALTER TABLE dbo.TTRILHAS
        ADD AVALIACAO_EFICACIA_ATUALIZADA_EM DATETIME2 NULL;
END;
