IF COL_LENGTH('dbo.TPROVAS', 'MODO_APLICACAO') IS NULL
BEGIN
    ALTER TABLE dbo.TPROVAS
        ADD MODO_APLICACAO VARCHAR(20) NULL;
END;

IF COL_LENGTH('dbo.TPROVAS', 'MODO_APLICACAO') IS NOT NULL
BEGIN
    UPDATE dbo.TPROVAS
    SET MODO_APLICACAO = 'coletiva'
    WHERE MODO_APLICACAO IS NULL OR LTRIM(RTRIM(MODO_APLICACAO)) = '';
END;

IF COL_LENGTH('dbo.TPROVAS', 'MODO_APLICACAO') IS NOT NULL
BEGIN
    ALTER TABLE dbo.TPROVAS
        ALTER COLUMN MODO_APLICACAO VARCHAR(20) NOT NULL;
END;

IF OBJECT_ID('DF_TPROVAS_MODO_APLICACAO', 'D') IS NULL
BEGIN
    ALTER TABLE dbo.TPROVAS
        ADD CONSTRAINT DF_TPROVAS_MODO_APLICACAO DEFAULT ('coletiva') FOR MODO_APLICACAO;
END;

IF OBJECT_ID('CK_TPROVAS_MODO_APLICACAO', 'C') IS NULL
BEGIN
    ALTER TABLE dbo.TPROVAS
        ADD CONSTRAINT CK_TPROVAS_MODO_APLICACAO
            CHECK (MODO_APLICACAO IN ('coletiva', 'individual'));
END;
