IF OBJECT_ID('dbo.TNOTIFICACOES_GESTAO', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TNOTIFICACOES_GESTAO (
        ID UNIQUEIDENTIFIER NOT NULL
            CONSTRAINT PK_TNOTIFICACOES_GESTAO PRIMARY KEY,
        USUARIO_CPF VARCHAR(100) NOT NULL,
        TIPO_MATERIAL VARCHAR(20) NOT NULL,
        MATERIAL_ID UNIQUEIDENTIFIER NOT NULL,
        MATERIAL_VERSAO INT NULL,
        NORMA_ID UNIQUEIDENTIFIER NOT NULL,
        TRILHA_ID UNIQUEIDENTIFIER NULL,
        DT_CONCLUSAO DATETIME2 NOT NULL,
        VENCE_EM DATETIME2 NOT NULL,
        CRIADO_EM DATETIME2 NOT NULL
            CONSTRAINT DF_TNOTIFICACOES_GESTAO_CRIADO_EM DEFAULT SYSUTCDATETIME(),
        LIDA_EM DATETIME2 NULL
    );
END;

IF COL_LENGTH('dbo.TNOTIFICACOES_GESTAO', 'LIDA_EM') IS NULL
BEGIN
    ALTER TABLE dbo.TNOTIFICACOES_GESTAO
        ADD LIDA_EM DATETIME2 NULL;
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_TNOTIFICACOES_GESTAO_TIPO'
      AND parent_object_id = OBJECT_ID('dbo.TNOTIFICACOES_GESTAO')
)
BEGIN
    ALTER TABLE dbo.TNOTIFICACOES_GESTAO
        ADD CONSTRAINT CK_TNOTIFICACOES_GESTAO_TIPO
            CHECK (TIPO_MATERIAL IN ('video', 'pdf'));
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_TNOTIFICACOES_GESTAO_STATUS'
      AND object_id = OBJECT_ID('dbo.TNOTIFICACOES_GESTAO')
)
BEGIN
    CREATE INDEX IX_TNOTIFICACOES_GESTAO_STATUS
        ON dbo.TNOTIFICACOES_GESTAO (LIDA_EM, VENCE_EM, CRIADO_EM DESC);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_TNOTIFICACOES_GESTAO_USUARIO'
      AND object_id = OBJECT_ID('dbo.TNOTIFICACOES_GESTAO')
)
BEGIN
    CREATE INDEX IX_TNOTIFICACOES_GESTAO_USUARIO
        ON dbo.TNOTIFICACOES_GESTAO (USUARIO_CPF, VENCE_EM DESC);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_TNOTIFICACOES_GESTAO_MATERIAL'
      AND object_id = OBJECT_ID('dbo.TNOTIFICACOES_GESTAO')
)
BEGIN
    CREATE INDEX IX_TNOTIFICACOES_GESTAO_MATERIAL
        ON dbo.TNOTIFICACOES_GESTAO (TIPO_MATERIAL, MATERIAL_ID, MATERIAL_VERSAO, VENCE_EM);
END;
