IF COL_LENGTH('dbo.TTRILHAS', 'PROCEDIMENTO_ID') IS NULL
BEGIN
    ALTER TABLE dbo.TTRILHAS
        ADD PROCEDIMENTO_ID UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('dbo.TTRILHAS', 'NORMA_ID') IS NULL
BEGIN
    ALTER TABLE dbo.TTRILHAS
        ADD NORMA_ID UNIQUEIDENTIFIER NULL;
END;
