IF OBJECT_ID('dbo.TTRILHA_SETOR_COMPARTILHAMENTOS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TTRILHA_SETOR_COMPARTILHAMENTOS (
        ID UNIQUEIDENTIFIER NOT NULL
            CONSTRAINT PK_TTRILHA_SETOR_COMPARTILHAMENTOS PRIMARY KEY,
        TRILHA_ID UNIQUEIDENTIFIER NOT NULL,
        MODULO_DESTINO_ID UNIQUEIDENTIFIER NOT NULL,
        COMPARTILHADO_POR NVARCHAR(255) NULL,
        COMPARTILHADO_EM DATETIME2 NOT NULL
            CONSTRAINT DF_TTRILHA_SETOR_COMPARTILHAMENTOS_EM DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_TTRILHA_SETOR_COMP_TRILHA
            FOREIGN KEY (TRILHA_ID) REFERENCES dbo.TTRILHAS (ID) ON DELETE CASCADE,
        CONSTRAINT FK_TTRILHA_SETOR_COMP_MODULO
            FOREIGN KEY (MODULO_DESTINO_ID) REFERENCES dbo.TMODULOS (ID) ON DELETE CASCADE
    );

    CREATE UNIQUE INDEX UX_TTRILHA_SETOR_COMP_TRILHA_MODULO
        ON dbo.TTRILHA_SETOR_COMPARTILHAMENTOS (TRILHA_ID, MODULO_DESTINO_ID);
END;
