IF COL_LENGTH('dbo.TCANAL_VIDEOS', 'TIPO_CONTEUDO') IS NULL
BEGIN
    ALTER TABLE dbo.TCANAL_VIDEOS
        ADD TIPO_CONTEUDO VARCHAR(20) NOT NULL
            CONSTRAINT DF_TCANAL_VIDEOS_TIPO_CONTEUDO DEFAULT ('video');
END;

IF COL_LENGTH('dbo.TCANAL_VIDEOS', 'PROCEDIMENTO_ID') IS NULL
BEGIN
    ALTER TABLE dbo.TCANAL_VIDEOS
        ADD PROCEDIMENTO_ID UNIQUEIDENTIFIER NULL;
END;

IF COL_LENGTH('dbo.TCANAL_VIDEOS', 'NORMA_ID') IS NULL
BEGIN
    ALTER TABLE dbo.TCANAL_VIDEOS
        ADD NORMA_ID UNIQUEIDENTIFIER NULL;
END;
