IF OBJECT_ID('dbo.TGESTAO_ARQUIVOS_SETOR_PASTAS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.TGESTAO_ARQUIVOS_SETOR_PASTAS (
    ID UNIQUEIDENTIFIER NOT NULL
      CONSTRAINT PK_TGESTAO_ARQUIVOS_SETOR_PASTAS PRIMARY KEY
      DEFAULT NEWID(),
    SHAREPOINT_ITEM_ID NVARCHAR(255) NOT NULL,
    SETOR NVARCHAR(120) NOT NULL,
    NOME NVARCHAR(255) NOT NULL,
    CAMINHO NVARCHAR(1000) NOT NULL,
    CRIADO_POR_NOME NVARCHAR(255) NULL,
    CRIADO_POR_EMAIL NVARCHAR(255) NULL,
    CRIADO_POR_USUARIO NVARCHAR(255) NULL,
    ATUALIZADO_POR_NOME NVARCHAR(255) NULL,
    ATUALIZADO_POR_EMAIL NVARCHAR(255) NULL,
    ATUALIZADO_POR_USUARIO NVARCHAR(255) NULL,
    CRIADO_EM DATETIME2(0) NOT NULL
      CONSTRAINT DF_TGESTAO_ARQUIVOS_SETOR_PASTAS_CRIADO_EM DEFAULT SYSUTCDATETIME(),
    ATUALIZADO_EM DATETIME2(0) NOT NULL
      CONSTRAINT DF_TGESTAO_ARQUIVOS_SETOR_PASTAS_ATUALIZADO_EM DEFAULT SYSUTCDATETIME()
  )

  CREATE UNIQUE INDEX UX_TGESTAO_ARQUIVOS_SETOR_PASTAS_SP_ITEM_ID
    ON dbo.TGESTAO_ARQUIVOS_SETOR_PASTAS (SHAREPOINT_ITEM_ID)

  CREATE UNIQUE INDEX UX_TGESTAO_ARQUIVOS_SETOR_PASTAS_SETOR_CAMINHO
    ON dbo.TGESTAO_ARQUIVOS_SETOR_PASTAS (SETOR, CAMINHO)

  CREATE INDEX IX_TGESTAO_ARQUIVOS_SETOR_PASTAS_SETOR_NOME
    ON dbo.TGESTAO_ARQUIVOS_SETOR_PASTAS (SETOR, NOME)
END
