IF OBJECT_ID('dbo.TUSUARIO_FACES', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TUSUARIO_FACES (
        ID UNIQUEIDENTIFIER NOT NULL,
        USUARIO_CPF VARCHAR(100) NOT NULL,
        DESCRIPTOR_JSON NVARCHAR(MAX) NOT NULL,
        FOTO_BASE64 NVARCHAR(MAX) NULL,
        FOTO_URL NVARCHAR(2000) NULL,
        ORIGEM VARCHAR(50) NULL,
        CRIADO_POR VARCHAR(100) NULL,
        CRIADO_EM DATETIME2 NOT NULL
            CONSTRAINT DF_TUSUARIO_FACES_CRIADO_EM DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_TUSUARIO_FACES PRIMARY KEY (ID),
        CONSTRAINT FK_TUSUARIO_FACES_USUARIO
            FOREIGN KEY (USUARIO_CPF) REFERENCES dbo.TUSUARIOS (CPF)
    );
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_TUSUARIO_FACES_CPF_CRIADO_EM'
      AND object_id = OBJECT_ID('dbo.TUSUARIO_FACES')
)
BEGIN
    CREATE INDEX IX_TUSUARIO_FACES_CPF_CRIADO_EM
        ON dbo.TUSUARIO_FACES (USUARIO_CPF, CRIADO_EM DESC);
END;
