IF COL_LENGTH('dbo.TUSUARIO_TREINAMENTOS', 'FACE_CONFIRMACAO_FOTO_BASE64') IS NULL
BEGIN
    ALTER TABLE dbo.TUSUARIO_TREINAMENTOS
        ADD FACE_CONFIRMACAO_FOTO_BASE64 NVARCHAR(MAX) NULL;
END;

IF COL_LENGTH('dbo.TUSUARIO_TREINAMENTOS', 'FACE_CONFIRMACAO_FOTO_URL') IS NULL
BEGIN
    ALTER TABLE dbo.TUSUARIO_TREINAMENTOS
        ADD FACE_CONFIRMACAO_FOTO_URL NVARCHAR(2000) NULL;
END;

IF COL_LENGTH('dbo.TUSUARIO_TREINAMENTOS', 'FACE_CONFIRMACAO_EM') IS NULL
BEGIN
    ALTER TABLE dbo.TUSUARIO_TREINAMENTOS
        ADD FACE_CONFIRMACAO_EM DATETIME2 NULL;
END;
