IF COL_LENGTH('dbo.TPROCEDIMENTOS', 'OBSERVACOES') IS NULL
BEGIN
    ALTER TABLE dbo.TPROCEDIMENTOS
        ADD OBSERVACOES NVARCHAR(MAX) NULL;
END;

IF COL_LENGTH('dbo.TNORMAS', 'OBSERVACOES') IS NULL
BEGIN
    ALTER TABLE dbo.TNORMAS
        ADD OBSERVACOES NVARCHAR(MAX) NULL;
END;
