IF OBJECT_ID('dbo.TGESTAO_ARQUIVOS_SETOR_USUARIO_ITENS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.TGESTAO_ARQUIVOS_SETOR_USUARIO_ITENS (
    ID UNIQUEIDENTIFIER NOT NULL
      CONSTRAINT PK_TGESTAO_ARQUIVOS_SETOR_USUARIO_ITENS PRIMARY KEY,
    SHAREPOINT_ITEM_ID NVARCHAR(255) NOT NULL,
    SETOR_VISUALIZACAO_CHAVE NVARCHAR(120) NOT NULL,
    SETOR_ORIGEM_CHAVE NVARCHAR(120) NOT NULL,
    RAIZ_COMPARTILHADA_ITEM_ID NVARCHAR(255) NULL,
    USUARIO NVARCHAR(255) NOT NULL,
    FAVORITO BIT NOT NULL
      CONSTRAINT DF_TGESTAO_ARQUIVOS_SETOR_USUARIO_ITENS_FAVORITO DEFAULT (0),
    ULTIMO_ACESSO_EM DATETIME2(0) NULL,
    CRIADO_EM DATETIME2(0) NOT NULL
      CONSTRAINT DF_TGESTAO_ARQUIVOS_SETOR_USUARIO_ITENS_CRIADO_EM DEFAULT SYSUTCDATETIME(),
    ATUALIZADO_EM DATETIME2(0) NOT NULL
      CONSTRAINT DF_TGESTAO_ARQUIVOS_SETOR_USUARIO_ITENS_ATUALIZADO_EM DEFAULT SYSUTCDATETIME()
  )

  CREATE UNIQUE INDEX UX_TGESTAO_ARQUIVOS_SETOR_USUARIO_ITENS_CHAVE
    ON dbo.TGESTAO_ARQUIVOS_SETOR_USUARIO_ITENS (SHAREPOINT_ITEM_ID, SETOR_VISUALIZACAO_CHAVE, USUARIO)

  CREATE INDEX IX_TGESTAO_ARQUIVOS_SETOR_USUARIO_ITENS_FAVORITOS
    ON dbo.TGESTAO_ARQUIVOS_SETOR_USUARIO_ITENS (SETOR_VISUALIZACAO_CHAVE, USUARIO, FAVORITO, ATUALIZADO_EM)

  CREATE INDEX IX_TGESTAO_ARQUIVOS_SETOR_USUARIO_ITENS_RECENTES
    ON dbo.TGESTAO_ARQUIVOS_SETOR_USUARIO_ITENS (SETOR_VISUALIZACAO_CHAVE, USUARIO, ULTIMO_ACESSO_EM)
END

IF OBJECT_ID('dbo.TGESTAO_ARQUIVOS_SETOR_LIXEIRA', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.TGESTAO_ARQUIVOS_SETOR_LIXEIRA (
    ID UNIQUEIDENTIFIER NOT NULL
      CONSTRAINT PK_TGESTAO_ARQUIVOS_SETOR_LIXEIRA PRIMARY KEY,
    SHAREPOINT_ITEM_ID NVARCHAR(255) NOT NULL,
    SETOR_CHAVE NVARCHAR(120) NOT NULL,
    NOME NVARCHAR(255) NOT NULL,
    CAMINHO NVARCHAR(1000) NOT NULL,
    TIPO_ITEM NVARCHAR(30) NOT NULL,
    EXTENSAO NVARCHAR(50) NULL,
    TAMANHO BIGINT NULL,
    WEB_URL NVARCHAR(1200) NULL,
    EXCLUIDO_POR_NOME NVARCHAR(255) NULL,
    EXCLUIDO_POR_EMAIL NVARCHAR(255) NULL,
    EXCLUIDO_POR_USUARIO NVARCHAR(255) NULL,
    EXCLUIDO_EM DATETIME2(0) NOT NULL
      CONSTRAINT DF_TGESTAO_ARQUIVOS_SETOR_LIXEIRA_EXCLUIDO_EM DEFAULT SYSUTCDATETIME()
  )

  CREATE UNIQUE INDEX UX_TGESTAO_ARQUIVOS_SETOR_LIXEIRA_ITEM
    ON dbo.TGESTAO_ARQUIVOS_SETOR_LIXEIRA (SHAREPOINT_ITEM_ID)

  CREATE INDEX IX_TGESTAO_ARQUIVOS_SETOR_LIXEIRA_SETOR
    ON dbo.TGESTAO_ARQUIVOS_SETOR_LIXEIRA (SETOR_CHAVE, EXCLUIDO_EM)
END
