export type LookupQuery = Record<string, string | undefined>;
export type LookupRow = Record<string, unknown>;

export type LookupDefinition = {
  code: string;
  fields: string;
  parameterKeys: string[];
};

export const DEFAULT_LIMIT = '50';
export const DEFAULT_SEARCH = '@';
export const DEFAULT_SEPARATOR = '-';

export const ENTRY_INVOICE_LOOKUPS: Record<string, LookupDefinition> = {
  coligada: {
    code: 'FL.DS.G.0014',
    fields: 'CODCOLIGADA&NOME&BUSCADOR',
    parameterKeys: ['BUSCADOR'],
  },
  filial: {
    code: 'FL.DS.G.0015',
    fields: 'CODCOLIGADA&CODFILIAL&NOME&ESTADO&BUSCADOR',
    parameterKeys: ['CODCOLIGADA', 'LIMITEFLUIG', 'BUSCADOR'],
  },
  localEstoque: {
    code: 'FL.DS.G.0018',
    fields: 'NOME&CODLOC&&BUSCADOR',
    parameterKeys: ['CODCOLIGADA', 'CODFILIAL', 'LIMITEFLUIG', 'BUSCADOR'],
  },
  centroCusto: {
    code: 'FL.DS.ENF.018',
    fields: 'NOME&CODCCUSTO&CODREDUZIDO&BUSCADOR',
    parameterKeys: ['CODCOLIGADA', 'LIMITEFLUIG', 'BUSCADOR'],
  },
  naturezaFiscal: {
    code: 'FL.DS.ENF.006',
    fields: 'NOME&IDNAT&CODNAT&BUSCADOR',
    parameterKeys: ['CODCOLIGADA', 'CODFILIAL', 'CODCOLCFO', 'CODCFO', 'LIMITEFLUIG', 'BUSCADOR'],
  },
  fornecedor: {
    code: 'FL.DS.ENF.019',
    fields: 'CODCOLIGADA&CODCFO&CGCCFO&NOMEFANTASIA&NOME&CODETD&BUSCADOR',
    parameterKeys: ['CODCOLIGADA', 'CODFILIAL', 'LIMITEFLUIG', 'BUSCADOR'],
  },
  fornecedorBaseCnpj: {
    code: 'FL.DS.ENF.007',
    fields: 'CODCOLIGADA&CODCFO&CGCCFO&NOMEFANTASIA&NOME&CODETD&BUSCADOR',
    parameterKeys: ['CODCOLIGADA', 'BASECNPJ', 'LIMITEFLUIG', 'BUSCADOR'],
  },
  movimento: {
    code: 'FL.DS.ENF.008',
    fields: 'CODTMV&NOME&CODTDO&LIBERADESCDESP&BUSCADOR',
    parameterKeys: ['CODCOLIGADA', 'LISTCODTMV', 'SEPARADOR', 'BUSCADOR'],
  },
  serie: {
    code: 'FL.DS.G.0019',
    fields: 'SERIE&PRINCIPAL',
    parameterKeys: ['CODCOLIGADA', 'CODTMV'],
  },
  paramMovimento: {
    code: 'FL.DS.ENF.014',
    fields:
      'CODTMV&NOME&SERIE&LIBERADESCDESP&CODTMVPED&CODTMVPED_DESC&LIBERADESCDESP_PED&CODTDO&' +
      'CODTB2FLX&CODTB2FLX_DESC&CODTB3FLX&CODTB3FLX_DESC&EDITAHISTORICOMOV&TIOPOHISTORICO&' +
      'NUMMAXIMOTITEM&TIPOITEM&ITEMREPETIDO&EDITAPRECOTOTAL&FINANCEIRO&' +
      'IDNAT&IDNAT_CODIGO&IDNAT_DESC&IDNATFORAESTADO&IDNATFORAESTADO_CODIGO&IDNATFORAESTADO_DESC',
    parameterKeys: ['CODCOLIGADA', 'CODTMV'],
  },
  condicaoPagto: {
    code: 'FL.DS.ENF.016',
    fields: 'CODCPG&NOME&BUSCADOR',
    parameterKeys: ['CODCOLIGADA', 'LIMITEFLUIG', 'BUSCADOR'],
  },
  parcelamento: {
    code: 'FL.DS.ENF.015',
    fields: 'ID&DATAVENCIMENTO&VALOR',
    parameterKeys: ['CODCPG', 'CODCOLIGADA', 'DATAEMISSAO', 'VALOR'],
  },
  estado: {
    code: 'FL.DS.ENF.013',
    fields: 'CODETD&NOME&BUSCADOR',
    parameterKeys: ['BUSCADOR'],
  },
  municipio: {
    code: 'FL.DS.ENF.012',
    fields: 'CODIGO&NOME&BUSCADOR',
    parameterKeys: ['CODETD', 'LIMITEFLUIG', 'BUSCADOR'],
  },
  purchaseOrder: {
    code: 'FL.DS.ENF.001',
    fields:
      'TMOV_T_CODCOLIGADA&TMOV_T_CODFILIAL&TMOV_T_IDMOV&TMOV_T_NUMEROMOV&TMOV_T_STATUS&' +
      'TMOV_T_CODTMV&TTMV_T_NOME&LIBERADESCDESP&CODTMVNF&DESCTMVNF&CODTDO&' +
      'TMOV_T_DATAEMISSAO&TMOV_T_CODLOC&TLOC_T_NOME&TMOV_T_CODCCUSTO&GCCUSTO_T_NOME&' +
      'TMOV_T_CODCPG&TMOV_T_DESCCPG&TMOV_T_CODCOLCFO&TMOV_T_CODCFO&FCFO_T_NOMEFANTASIA&' +
      'FCFO_T_NOME&FCFO_T_CGCCFO&FCFO_T_CODETD&TIPOORDEMCOMPRA&DESCTIPOORDEMCOMPRA&' +
      'TMOV_T_HISTORICOCURTO&TMOV_T_VALORDESP&TMOV_T_VALORDESC&TMOV_T_VALORFRETE&' +
      'TMOV_T_VALORBRUTO&TMOV_T_VALORLIQUIDO&TMOV_T_FRETECIFOUFOB&BUSCADOR',
    parameterKeys: [
      'CODCOLIGADA',
      'CODFILIAL',
      'CODCOLCFO',
      'CODCFO',
      'LISTIDMOVREMOVE',
      'SEPARADOR',
      'LIMITEFLUIG',
      'BUSCADOR',
      'IDMOVDESTEXCEP',
    ],
  },
  purchaseOrderItems: {
    code: 'FL.DS.ENF.002',
    fields:
      'TITMMOV_T_NSEQITMMOV&TITMMOV_T_IDPRD&TITMMOV_T_IDMOV&TITMMOV_T_CODIGOPRD&TITMMOV_T_NOMEFANTASIA&' +
      'TITMMOV_T_CODUND&TITMMOV_T_TIPO&TITMMOV_T_PRECOUNITARIO&TITMMOV_T_QUANTIDADE&TITMMOV_T_VALORBRUTOITEM&' +
      'TITMMOV_T_VALORSALDO&TITMMOV_T_QUANTIDADEARECEBER&TOLERANCIA&TITMMOV_T_VALORRETENCAO&TITMMOV_T_HISTORICO&' +
      'TITMMOV_T_CODNOFORN&TITMMOV_T_CODCCUSTO&GCCUSTO_T_NOME&TITMMOV_T_CODCOLTBORCAMENTO&TITMMOV_T_CODTBORCAMENTO&' +
      'TITMMOV_T_DESCTBORCAMENTO&TPRODUTODEF_T_CODCOLTBORCAMENTO&TPRODUTODEF_T_CODTBORCAMENTO&TPRODUTODEF_T_DESCTBORCAMENTO',
    parameterKeys: ['CODCOLIGADA', 'LISTIDMOV', 'SEPARADOR', 'IDMOVDESTEXCEP'],
  },
  purchaseOrderApport: {
    code: 'FL.DS.ENF.003',
    fields:
      'TITMMOVRATCCU_T_CODCOLIGADA&TITMMOVRATCCU_T_IDMOV&TITMMOVRATCCU_T_NSEITMMOV&' +
      'TITMMOVRATCCU_T_CODCCUSTO&TITMMOVRATCCU_T_NOME&TITMMOVRATCCU_T_PERCENTUAL&' +
      'TITMMOVRATCCU_T_VALOR&TITMMOVRATCCU_T_VALORORIGINALITEM&TITMMOVRATCCU_T_STATUSFAT&' +
      'TITMMOVRATCCU_T_IDTRF&TITMMOVRATCCU_T_CODTRF&TITMMOVRATCCU_T_NOMETRF&' +
      'TITMMOVRATCCU_T_IDPRJ&TITMMOVRATCCU_T_CODPRJ&TITMMOVRATCCU_T_NOMEPRJ',
    parameterKeys: ['CODCOLIGADA', 'IDMOV'],
  },
  purchaseOrderApportEspecific: {
    code: 'FL.DS.ENF.003.1',
    fields:
      'TITMMOVRATCCU_T_CODCOLIGADA&TITMMOVRATCCU_T_IDMOV&TITMMOVRATCCU_T_NSEITMMOV&' +
      'TITMMOVRATCCU_T_CODCCUSTO&TITMMOVRATCCU_T_NOME&TITMMOVRATCCU_T_PERCENTUAL&' +
      'TITMMOVRATCCU_T_VALOR&TITMMOVRATCCU_T_VALORORIGINALITEM&TITMMOVRATCCU_T_STATUSFAT&' +
      'TITMMOVRATCCU_T_IDTRF&TITMMOVRATCCU_T_CODTRF&TITMMOVRATCCU_T_NOMETRF&' +
      'TITMMOVRATCCU_T_IDPRJ&TITMMOVRATCCU_T_CODPRJ&TITMMOVRATCCU_T_NOMEPRJ',
    parameterKeys: ['CODCOLIGADA', 'IDMOV', 'NSEQITMMOV'],
  },
  taxes: {
    code: 'FL.DS.ENF.004',
    fields: 'CODTRB&DESCRICAO&SITTRIBUTARIA&TIPORECOLHIMENTO',
    parameterKeys: ['CODCOLIGADA', 'CODTMV'],
  },
  taxesAliquotas: {
    code: 'FL.DS.ENF.005',
    fields:
      'IDMOV&NSEQITMMOV&CODTRB&DESCRICAO&SITTRIBUTARIA&BASEDECALCULO&ALIQUOTA&TIPORECOLHIMENTO&VALOR',
    parameterKeys: ['CODCOLIGADA', 'CODTMV', 'LISTPRODUTO', 'SEPARADORLIST', 'SEPARADOR'],
  },
  formaPagto: {
    code: 'FL.DS.ENF.010',
    fields:
      'TFORMAPAGTO_T_IDFORMAPAGTO&TFORMAPAGTO_T_CODFORMAPAGTO&TFORMAPAGTO_T_DESCFORMAPAGTO&' +
      'TFORMAPAGTO_T_TIPOPFORMAPAGTO&TFORMAPAGTO_T_CODCOLCXA&TFORMAPAGTO_T_CODCXA&TFORMAPAGTO_T_DESCCXA&TFORMAPAGTO_T_TAXAADMIN',
    parameterKeys: ['CODCOLIGADA', 'CODCOLCFO', 'CODCFO'],
  },
  formaPagtoResumo: {
    code: 'FL.DS.ENF.010',
    fields: 'IDPGTO&DESCRICAO',
    parameterKeys: ['CODCOLIGADA', 'CODCOLCFO', 'CODCFO'],
  },
  codCxa: {
    code: 'FL.DS.ENF.011',
    fields: 'CODCXA&CODCOLCXA&DESCRICAO',
    parameterKeys: ['CODCOLIGADA'],
  },
  lancamentosFinanceiros: {
    code: 'FL.DS.ENF.024',
    fields: 'IDMOV',
    parameterKeys: ['CODCOLIGADA'],
  },
  detalhesTipoPagamento: {
    code: 'FL.DS.ENF.026',
    fields:
      'CODCOLIGADA&CODCOLCFO&CODCFO&IDPGTO&DESCRICAO&FORMAPAGAMENTO&NUMEROBANCO&CODIGOAGENCIA&' +
      'DIGITOAGENCIA&CONTACORRENTE&DIGITOCONTA&NOMEAGENCIA&CAMARACOMPENSACAO&TIPOCONTA&TIPODOC&' +
      'CODFINALIDADE&FAVORECIDO&CGCFAVORECIDO&ATIVO&CODFILIAL&CHAVE&TIPOPIX',
    parameterKeys: ['CODCOLIGADA', 'CODCOLCFO', 'CODCFO', 'IDPGTO'],
  },
};
