const SERASA_PEFIN_STATUS = Object.freeze({
  PENDENTE_ENVIO: 'PENDENTE_ENVIO',
  ENVIADO_SERASA: 'ENVIADO_SERASA',
  AGUARDANDO_RETORNO: 'AGUARDANDO_RETORNO',
  NEGATIVADO_SUCESSO: 'NEGATIVADO_SUCESSO',
  NEGATIVADO_ERRO: 'NEGATIVADO_ERRO',
});

const SERASA_PEFIN_STATUS_VALUES = Object.freeze(Object.values(SERASA_PEFIN_STATUS));

const SERASA_PEFIN_TIPO_REGISTRO = Object.freeze({
  PRINCIPAL: 'PRINCIPAL',
  GARANTIDOR: 'GARANTIDOR',
});

const SERASA_PEFIN_TIPO_REGISTRO_VALUES = Object.freeze(
  Object.values(SERASA_PEFIN_TIPO_REGISTRO)
);

module.exports = {
  SERASA_PEFIN_STATUS,
  SERASA_PEFIN_STATUS_VALUES,
  SERASA_PEFIN_TIPO_REGISTRO,
  SERASA_PEFIN_TIPO_REGISTRO_VALUES,
};
